### ISSUE TITLE
大神求一个数据库脚本

### ISSUE THREAD

**Issue by FengSenHua** [jerryshell/live-teaching-platform#2]

**Comment by jerryshell** [comment]
这个项目的持久层框架是 Spring Data JPA，你自己建一个名为 `upload_video` 的库就行，第一次运行会自己建表。
其他的配置可以看 `src/main/resources/application.properties` 文件。

**Comment by FengSenHua** [comment]
你好能加个QQ吗？我有一些技术上的问题想问一下你


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jerry"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月4日(星期一) 晚上9:50
收件人:&nbsp;"jerryshell/live-teaching-platform"<live-teaching-platform@noreply.github.com&gt;;
抄送:&nbsp;"SH_"<1146977578@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jerryshell/live-teaching-platform] 大神求一个数据库脚本 (#2)




这个项目的持久层框架是 Spring Data JPA，你自己建一个名为 upload_video 的库就行，第一次运行会自己建表。
 其他的配置可以看 src/main/resources/application.properties 文件。

**Comment by jerryshell** [comment]
我不使用 QQ，有问题可以用邮箱一起交流：calljerryli@outlook.com
