### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by wang-wyy** [jerryshell/live-teaching-platform#3]
请您帮我指导一下，能不能加我一下qq519889245
或者我加你

**Comment by jerryshell** [comment]
有问题可以直接在这里留言或者使用邮箱联系：calljerryli@outlook.com

**Comment by wang-wyy** [comment]
nginx配置就直接把你程序当中的那个加进去吗？
还有srs是要到linux虚拟机上搭建吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jerry"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 晚上8:59
收件人: "jerryshell/live-teaching-platform"<live-teaching-platform@noreply.github.com&gt;; 
抄送: "王菜鸟"<519889245@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jerryshell/live-teaching-platform] 你好 (#3)





 
有问题可以直接在这里留言或者使用邮箱联系：calljerryli@outlook.com

**Comment by jerryshell** [comment]
1. Nginx 的配置主要是做了反向代理来解决跨域的问题，如果你会配反向代理的话可以自己写 Nginx 的配置，项目里的只是参考。
2. SRS 在文档里的系统要求是 Linux，如果要在 Windows 上搭建可以使用 Docker。

**Comment by wang-wyy** [comment]
我还没学到这些，我的毕设要做直播功能，时间太紧了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jerry"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 晚上9:15
收件人: "jerryshell/live-teaching-platform"<live-teaching-platform@noreply.github.com&gt;; 
抄送: "王菜鸟"<519889245@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jerryshell/live-teaching-platform] 你好 (#3)





  
Nginx 的配置主要是做了反向代理来解决跨域的问题，如果你会配反向代理的话可以自己写 Nginx 的配置，项目里的只是参考。
 
SRS 在文档里的系统要求是 Linux，如果要在 Windows 上搭建可以使用 Docker。

**Comment by wang-wyy** [comment]
nginx配置好之后需要把html放到nginx目录下的html文件夹中吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jerry"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 晚上9:15
收件人: "jerryshell/live-teaching-platform"<live-teaching-platform@noreply.github.com&gt;; 
抄送: "王菜鸟"<519889245@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jerryshell/live-teaching-platform] 你好 (#3)





  
Nginx 的配置主要是做了反向代理来解决跨域的问题，如果你会配反向代理的话可以自己写 Nginx 的配置，项目里的只是参考。
 
SRS 在文档里的系统要求是 Linux，如果要在 Windows 上搭建可以使用 Docker。

**Comment by jerryshell** [comment]
不需要，Nginx 只是将业务后端（Java）和视频流（SRS）连接起来的桥梁，因为这两个服务开在不同的端口，会造成跨域问题，所以需要 Nginx 进行反向代理。

**Comment by jerryshell** [comment]
如果你的业务后端已经写得差不多，只差一个直播服务的话。我建议你直接去看 SRS 的文档。然后想办法把 SRS 接入自己的系统中。

**Comment by jerryshell** [comment]
我刚才看了一下。
最新版的 SRS 3.0 已经解决了跨域的问题。
所以现在应该不需要额外配置 Nginx 了。
我的建议还是那句话：「直接去看 SRS 的文档，然后想办法把 SRS 接入自己的系统中」。

**Comment by wang-wyy** [comment]
好的我去看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jerry"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 晚上9:45
收件人: "jerryshell/live-teaching-platform"<live-teaching-platform@noreply.github.com&gt;; 
抄送: "王菜鸟"<519889245@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jerryshell/live-teaching-platform] 你好 (#3)





 
我刚才看了一下。
 最新版的 SRS 3.0 已经解决了跨域的问题。
 所以现在应该不需要额外配置 Nginx 了。
 我的建议还是那句话：「直接去看 SRS 的文档，然后想办法把 SRS 接入自己的系统中」。

**Comment by wang-wyy** [comment]
现在我有点看不懂，想先把你的代码运行起来，搞搞再看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jerry"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 晚上9:45
收件人: "jerryshell/live-teaching-platform"<live-teaching-platform@noreply.github.com&gt;; 
抄送: "王菜鸟"<519889245@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jerryshell/live-teaching-platform] 你好 (#3)





 
我刚才看了一下。
最新版的 SRS 3.0 已经解决了跨域的问题。
所以现在应该不需要额外配置 Nginx 了。
我的建议还是那句话：「直接去看 SRS 的文档，然后想办法把 SRS 接入自己的系统中」。

**Comment by jerryshell** [comment]
这个项目的代码使用了 Spring Boot 框架。建议先去熟悉这个框架再回来看。

**Comment by wang-wyy** [comment]
恩我看过了能看懂点springboot




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jerry"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 晚上10:14
收件人: "jerryshell/live-teaching-platform"<live-teaching-platform@noreply.github.com&gt;; 
抄送: "王菜鸟"<519889245@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jerryshell/live-teaching-platform] 你好 (#3)





 
这个项目的代码使用了 Spring Boot 框架。建议先去熟悉这个框架再回来看。

**Comment by wang-wyy** [comment]
上传视频和照片出错，找不到那个路径请问怎么办，
 &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jerry"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 晚上10:14
收件人: "jerryshell/live-teaching-platform"<live-teaching-platform@noreply.github.com&gt;; 
抄送: "王菜鸟"<519889245@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jerryshell/live-teaching-platform] 你好 (#3)





 
这个项目的代码使用了 Spring Boot 框架。建议先去熟悉这个框架再回来看。

**Comment by jerryshell** [comment]
这些配置都在 `src/main/resources/application.properties` 这个文件里，你要根据自己的环境改这些配置。

**Comment by jerryshell** [comment]
Close inactive issue.
