### ISSUE TITLE
hello, 能否分享一下DB表结构？

### ISSUE THREAD

**Issue by ljm653467080** [jerryshell/live-teaching-platform#4]
hello, 能否分享一下DB表结构？

**Comment by jerryshell** [comment]
关于数据库建表可以看这里：https://github.com/jerryshell/live-teaching-platform/issues/2#issuecomment-549361930

已经关闭的 issue 应该会有一些你想要的答案：https://github.com/jerryshell/live-teaching-platform/issues?q=is%3Aissue+is%3Aclosed
